-- ============================================================================
-- SeerPlay Intelligence Hub — Oracle 26ai Free Schema
-- ============================================================================
-- Fixes:
--   1. Uses USERS tablespace (ASSM) instead of SYSTEM for VECTOR/JSON support
--   2. Removes DBMS_CLOUD/DBMS_CLOUD_AI (not available in Free edition)
--   3. Creates a dedicated SEERPLAY user
-- ============================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

-- ============================================================================
-- 0. CREATE DEDICATED USER (in USERS tablespace which supports ASSM)
-- ============================================================================
CREATE USER seerplay IDENTIFIED BY SeerPlay123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO seerplay;
GRANT CREATE VIEW TO seerplay;
GRANT CREATE SESSION TO seerplay;
GRANT CREATE PROPERTY GRAPH TO seerplay;
GRANT CREATE MINING MODEL TO seerplay;

-- Switch to the new user's schema
ALTER SESSION SET CURRENT_SCHEMA = seerplay;

-- ============================================================================
-- 1. PLAYERS TABLE
-- ============================================================================
CREATE TABLE seerplay.players (
    player_id    VARCHAR2(50) PRIMARY KEY,
    username     VARCHAR2(100),
    signup_date  DATE DEFAULT SYSDATE,
    persona      VARCHAR2(20),
    ltv          NUMBER(10,2) DEFAULT 0,
    status       VARCHAR2(20) DEFAULT 'ACTIVE'
) TABLESPACE users;

-- ============================================================================
-- 2. PLAYER SESSIONS (with VECTOR column for behavior embeddings)
-- ============================================================================
CREATE TABLE seerplay.player_sessions (
    session_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id        VARCHAR2(50) REFERENCES seerplay.players(player_id),
    session_start    TIMESTAMP DEFAULT SYSTIMESTAMP,
    session_end      TIMESTAMP,
    total_bets       NUMBER(10,2) DEFAULT 0,
    total_wins       NUMBER(10,2) DEFAULT 0,
    total_losses     NUMBER(10,2) DEFAULT 0,
    game_type        VARCHAR2(50),
    device           VARCHAR2(30),
    behavior_vector  VECTOR(768, FLOAT32),
    aggression_score NUMBER(3) DEFAULT 0,
    variance_level   VARCHAR2(20) DEFAULT 'Low'
) TABLESPACE users;

-- ============================================================================
-- 3. SESSION EVENTS (high-velocity clickstream with JSON)
-- ============================================================================
CREATE TABLE seerplay.session_events (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    NUMBER REFERENCES seerplay.player_sessions(session_id),
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    event_ts      TIMESTAMP DEFAULT SYSTIMESTAMP,
    event_type    VARCHAR2(30),
    event_data    JSON
) TABLESPACE users;

-- ============================================================================
-- 4. MODEL CENTROIDS (for AI Vector Search)
-- ============================================================================
CREATE TABLE seerplay.model_centroids (
    persona          VARCHAR2(20) PRIMARY KEY,
    centroid_vector   VECTOR(768, FLOAT32),
    player_count     NUMBER DEFAULT 0,
    avg_ltv          NUMBER(10,2) DEFAULT 0
) TABLESPACE users;

-- ============================================================================
-- 5. WHAT-IF MODEL (pre-computed regression coefficients)
-- ============================================================================
CREATE TABLE seerplay.whatif_model (
    model_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name       VARCHAR2(100),
    intercept        NUMBER(12,4),
    coeff_session_dur NUMBER(12,6),
    coeff_avg_bet     NUMBER(12,6),
    coeff_loss_streak NUMBER(12,6),
    coeff_break_mins  NUMBER(12,6),
    r_squared        NUMBER(8,6),
    trained_on       TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE users;

-- ============================================================================
-- 6. PROPERTY GRAPH — Node Tables
-- ============================================================================

-- Devices (shared across players for fraud detection)
CREATE TABLE seerplay.devices (
    device_id    VARCHAR2(50) PRIMARY KEY,
    device_type  VARCHAR2(30),
    fingerprint  VARCHAR2(100)
) TABLESPACE users;

-- IP Addresses
CREATE TABLE seerplay.ip_addrs (
    ip_id        VARCHAR2(50) PRIMARY KEY,
    ip_address   VARCHAR2(45),
    country      VARCHAR2(5)
) TABLESPACE users;

-- Games catalog
CREATE TABLE seerplay.games (
    game_id      VARCHAR2(50) PRIMARY KEY,
    game_name    VARCHAR2(100),
    game_theme   VARCHAR2(50)
) TABLESPACE users;

-- ============================================================================
-- 7. PROPERTY GRAPH — Edge Tables
-- ============================================================================

-- Player ↔ Device (many-to-many; shared devices = fraud signal)
CREATE TABLE seerplay.uses_device (
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    device_id     VARCHAR2(50) REFERENCES seerplay.devices(device_id),
    session_count NUMBER DEFAULT 1,
    PRIMARY KEY (player_id, device_id)
) TABLESPACE users;

-- Player ↔ IP (many-to-many; shared IPs = collusion signal)
CREATE TABLE seerplay.logs_from_ip (
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    ip_id         VARCHAR2(50) REFERENCES seerplay.ip_addrs(ip_id),
    first_seen    DATE DEFAULT SYSDATE,
    last_seen     DATE DEFAULT SYSDATE,
    PRIMARY KEY (player_id, ip_id)
) TABLESPACE users;

-- Player → Game (play history for recommendations)
CREATE TABLE seerplay.plays_game (
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    game_id       VARCHAR2(50) REFERENCES seerplay.games(game_id),
    total_bets    NUMBER(10,2) DEFAULT 0,
    session_count NUMBER DEFAULT 0,
    PRIMARY KEY (player_id, game_id)
) TABLESPACE users;

-- Player → Player (referral chains for influence analysis)
CREATE TABLE seerplay.referrals (
    referrer_id   VARCHAR2(50) REFERENCES seerplay.players(player_id),
    referee_id    VARCHAR2(50) REFERENCES seerplay.players(player_id),
    referral_date DATE DEFAULT SYSDATE,
    PRIMARY KEY (referrer_id, referee_id)
) TABLESPACE users;

-- Player → Risk Event (self-exclusion, failed deposits, cooldowns)
CREATE TABLE seerplay.risk_events (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    risk_type     VARCHAR2(30),
    event_date    DATE DEFAULT SYSDATE,
    severity      NUMBER(1) DEFAULT 1
) TABLESPACE users;

-- Player Notes (Host Intel)
CREATE TABLE seerplay.player_notes (
    note_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id     VARCHAR2(50) REFERENCES seerplay.players(player_id),
    note_text     VARCHAR2(1000),
    author        VARCHAR2(50) DEFAULT 'System',
    created_at    DATE DEFAULT SYSDATE,
    note_type     VARCHAR2(20) DEFAULT 'NOTE', -- 'NOTE' or 'ALERT'
    alert_type    VARCHAR2(50) -- e.g., 'HIGH TILT SIGNS'
) TABLESPACE users;

-- ============================================================================
-- 8. JSON-RELATIONAL DUALITY VIEWS
-- ============================================================================
-- Session Events Duality View: App writes JSON, Oracle stores relationally
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW seerplay.session_event_dv AS
SELECT JSON {
    '_id'        : e.event_id,
    'sessionId'  : e.session_id,
    'playerId'   : e.player_id,
    'timestamp'  : e.event_ts,
    'eventType'  : e.event_type,
    'data'       : e.event_data
}
FROM seerplay.session_events e WITH INSERT UPDATE DELETE;

-- Player Sessions Duality View (read-oriented)
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW seerplay.player_session_dv AS
SELECT JSON {
    '_id'           : ps.session_id,
    'playerId'      : ps.player_id,
    'sessionStart'  : ps.session_start,
    'sessionEnd'    : ps.session_end,
    'totalBets'     : ps.total_bets,
    'totalWins'     : ps.total_wins,
    'totalLosses'   : ps.total_losses,
    'gameType'      : ps.game_type,
    'device'        : ps.device,
    'aggression'    : ps.aggression_score,
    'variance'      : ps.variance_level
}
FROM seerplay.player_sessions ps WITH INSERT UPDATE DELETE;

-- ============================================================================
-- 9. INDEXES
-- ============================================================================
CREATE INDEX seerplay.idx_sessions_player ON seerplay.player_sessions(player_id);
CREATE INDEX seerplay.idx_events_session ON seerplay.session_events(session_id);
CREATE INDEX seerplay.idx_events_player  ON seerplay.session_events(player_id);
CREATE INDEX seerplay.idx_events_type    ON seerplay.session_events(event_type);
CREATE INDEX seerplay.idx_risk_player    ON seerplay.risk_events(player_id);
CREATE INDEX seerplay.idx_notes_player   ON seerplay.player_notes(player_id);

-- ============================================================================
-- 10. PROPERTY GRAPH DEFINITION (SQL/PGQ)
-- ============================================================================
-- This graph connects Players to Devices, IPs, Games, other Players (referrals),
-- and Risk Events, enabling SQL/PGQ traversal queries for fraud, influence, and risk.

CREATE PROPERTY GRAPH seerplay.seerplay_graph
  VERTEX TABLES (
    seerplay.players
      KEY (player_id)
      PROPERTIES (player_id, username, persona, ltv, status),
    seerplay.devices
      KEY (device_id)
      PROPERTIES (device_id, device_type, fingerprint),
    seerplay.ip_addrs
      KEY (ip_id)
      PROPERTIES (ip_id, ip_address, country),
    seerplay.games
      KEY (game_id)
      PROPERTIES (game_id, game_name, game_theme)
  )
  EDGE TABLES (
    seerplay.uses_device
      KEY (player_id, device_id)
      SOURCE KEY (player_id) REFERENCES players (player_id)
      DESTINATION KEY (device_id) REFERENCES devices (device_id)
      PROPERTIES (session_count),
    seerplay.logs_from_ip
      KEY (player_id, ip_id)
      SOURCE KEY (player_id) REFERENCES players (player_id)
      DESTINATION KEY (ip_id) REFERENCES ip_addrs (ip_id)
      PROPERTIES (first_seen, last_seen),
    seerplay.plays_game
      KEY (player_id, game_id)
      SOURCE KEY (player_id) REFERENCES players (player_id)
      DESTINATION KEY (game_id) REFERENCES games (game_id)
      PROPERTIES (total_bets, session_count),
    seerplay.referrals
      KEY (referrer_id, referee_id)
      SOURCE KEY (referrer_id) REFERENCES players (player_id)
      DESTINATION KEY (referee_id) REFERENCES players (player_id)
      PROPERTIES (referral_date)
  );

COMMIT;

